### PR TITLE
chore: add Talisman

### PR DESCRIPTION
**Pull request by 0xKheops**
We released today version 1.19.0 of Talisman, which includes EIP-6963 support

image

### CODE REVIEW

**Comment by glitch-txs** [comment]
Let's gooooo! 😸🎉

**Review by boidushya — COMMENTED** [review]
Congrats on the release team!
However, I'd like you to know that theres some compat issues with other extensions most likely originating from dual support for LegacyProvider. Let's get this PR merged once thats resolved!
Attached screenshot of Talisman failing to show up when multiple other wallets are installed. However, it does work by itself. 
image

**Comment by 0xKheops** [comment]
Thanks for reporting this, will fix ASAP and update here when done :)

**Comment by boidushya** [comment]
Thanks for the clarity @0xKheops !
Here's how enKrypt Wallet does it for [reference](https://github.com/enkryptcom/enKrypt/blob/e90f867c73ecdcbb7881aff48427e6cdb568cae8/packages/extension/src/providers/ethereum/inject.ts#L15)

**Comment by 0xKheops** [comment]
@boidushya we released the fix today in Talisman v1.19.1

May you please give it another try ? :)

**Review by boidushya — APPROVED** [review]
LGTM!

**Pull request merged**
