### PR TITLE
Add Xdefi connector

### PR DESCRIPTION
**Pull request by zdeadex**

### CODE REVIEW

**Comment by boidushya** [comment]
Hey!
image
Looks like the icon provided is in a `.png` format, could you please update it to be a base64 data URI?
image
[More info](https://eips.ethereum.org/EIPS/eip-6963#provider-info)

**Comment by boidushya** [comment]
Also looks like `rdns` field is missing from [provider details](https://eips.ethereum.org/EIPS/eip-6963#provider-info)

**Comment by boidushya** [comment]
@zdeadex 
Quick clarity: the existing svg for this repo was fine, what the specs indicate is to update the svg and rdns on your wallets EIP6963 injection script

**Comment by boidushya** [comment]
@zdeadex 
By wallet Injection Script i meant the one announced by your wallet, not over here on the dapp 👀

**Comment by zdeadex** [comment]
> @zdeadex By wallet Injection Script i meant the one announced by your wallet, not over here on the dapp 👀

Owh ok, very sorry for the confusion we will check that

**Comment by zdeadex** [comment]
> @zdeadex By wallet Injection Script i meant the one announced by your wallet, not over here on the dapp 👀

Pushed on our side

**Review by glitch-txs — APPROVED** [review]
Issues were properly addressed.

**Pull request merged**
